version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://fiscalizaai_user:ONWzd9CNt6G0XEEM1aDny3tjoPmAmX9A@dpg-d1amef3ipnbc73aa0r9g-a.oregon-postgres.render.com/fiscalizaai
